### ISSUE TITLE
[FEATURE] Grab information from GH Actions

### ISSUE THREAD

**Issue by guibranco** [guibranco/projects-monitor#16]
#### **Description:**

We need to create an integration with the [GitHub Actions API](https://docs.github.com/en/rest/actions/workflows) to retrieve information about workflows for each repository. The integration will query the repositories table to get a list of repositories, call the GitHub API to fetch workflows for each repository, and store the relevant results in a new dedicated table. The table will store key workflow information (e.g., workflow name, last run status, and last run timestamp), avoiding detailed data to keep it lightweight.

#### **Objectives:**

1. **Create GitHub Actions API Integration:**
   - Develop a PHP integration class to interact with the GitHub Actions API for fetching workflows.

2. **Query the Repositories Table:**
   - Retrieve the list of repositories from the existing repositories table.

3. **Call the GitHub Actions API for Each Repository:**
   - Use the GitHub API to fetch workflow information for each repository.

4. **Create a New Database Table:**
   - Design a new table to store only the relevant workflow data fetched from GitHub Actions (e.g., workflow name, last run status, last run timestamp).

5. **Store Relevant Data:**
   - Parse the API response and insert key workflow information into the new table.

#### **Tasks:**

- [ ] Develop a PHP integration class for the GitHub Actions API.
- [ ] Query the repositories table to fetch the list of repositories.
- [ ] Fetch workflows for each repository using the GitHub API.
- [ ] Create a new table in the database to store relevant workflow information (workflow name, last run status, last run timestamp, etc.).
- [ ] Parse the response and store the data in the new table.
- [ ] Ensure the process runs periodically to keep the workflow data updated.

#### **Code Example:**

Here’s a pseudo-code example of how the integration might work:

```php
// Fetch repositories from the database
$repositories = $database->query('SELECT id, name FROM repositories');

// Instantiate GitHub API integration class
$github = new GitHubIntegration('YOUR_GITHUB_TOKEN');

foreach ($repositories as $repository) {
    // Call GitHub Actions API to fetch workflows for each repository
    $workflows = $github->fetchWorkflows($repository['name']);
    
    foreach ($workflows as $workflow) {
        // Parse relevant fields from the workflow data
        $workflowName = $workflow['name'];
        $lastRunStatus = $workflow['last_run']['status'];
        $lastRunTimestamp = $workflow['last_run']['timestamp'];

        // Insert the relevant data into the new table
        $database->query('INSERT INTO github_workflows (repository_id, workflow_name, last_run_status, last_run_timestamp) 
                          VALUES (?, ?, ?, ?)', 
                          [$repository['id'], $workflowName, $lastRunStatus, $lastRunTimestamp]);
    }
}
```

#### **Acceptance Criteria:**

- [ ] A PHP integration class with the GitHub Actions API is created.
- [ ] The repositories table is queried to retrieve the list of repositories.
- [ ] Workflow data (e.g., workflow name, last run status, last run timestamp) is fetched from GitHub Actions and stored in a new table.
- [ ] The new table is created with relevant fields to store GitHub Actions workflow data.
- [ ] The process runs periodically to keep the workflow information up to date.

#### **Additional Context:**

By integrating with the GitHub Actions API, we will be able to monitor the status and last run times of workflows for each repository. This information will help ensure that workflows are running as expected and can be used for reporting purposes in dashboards.
