### ISSUE TITLE
[FEATURE] Grab information from CodeClimate

### ISSUE THREAD

**Issue by guibranco** [guibranco/projects-monitor#20]
#### **Description:**

We need to create an integration with the [CodeClimate API](https://developer.codeclimate.com/#overview) to fetch and store relevant information for each of our repositories. The process should query the existing repositories table, call the CodeClimate API for each repository, and store the results in a new dedicated table. This table will only store key information (e.g., quality score, issues count, maintainability index), and not the full detailed data from the API.

#### **Objectives:**

1. **Create CodeClimate API Integration:**
   - Develop an integration class in PHP to interact with the CodeClimate API.

2. **Query the Repositories Table:**
   - Retrieve the list of repositories from the existing repositories table.

3. **Call the CodeClimate API for Each Repository:**
   - Use the new CodeClimate integration to fetch repository metrics (e.g., maintainability, technical debt, GPA, issues count).

4. **Create a New Database Table:**
   - Create a new dedicated table to store the relevant CodeClimate data.

5. **Store Relevant Data:**
   - Parse the API response and insert only key information into the new table.

#### **Tasks:**

- [ ] Develop a new PHP class to integrate with the CodeClimate API.
- [ ] Query the repositories table to get the list of repositories.
- [ ] Fetch CodeClimate data for each repository by calling the API.
- [ ] Create a new database table for storing CodeClimate data (fields: repository ID, quality score, maintainability index, issues count, etc.).
- [ ] Insert the relevant data from the API response into the new table.
- [ ] Ensure that the new functionality runs periodically to keep CodeClimate data up to date.

#### **Code Example:**

Here’s a basic pseudo-code example to illustrate the integration process:

```php
// Fetch repositories from the database
$repositories = $database->query('SELECT id, name FROM repositories');

// Instantiate CodeClimate integration class
$codeClimate = new CodeClimateIntegration('YOUR_API_KEY');

foreach ($repositories as $repository) {
    // Call CodeClimate API for each repository
    $codeClimateData = $codeClimate->fetchRepositoryData($repository['name']);
    
    // Parse relevant fields from the API response
    $gpa = $codeClimateData['data']['attributes']['gpa'];
    $issuesCount = $codeClimateData['data']['attributes']['issues_count'];
    $maintainability = $codeClimateData['data']['attributes']['maintainability'];

    // Store the relevant data in the new table
    $database->query('INSERT INTO codeclimate_info (repository_id, gpa, issues_count, maintainability) 
                      VALUES (?, ?, ?, ?)', 
                      [$repository['id'], $gpa, $issuesCount, $maintainability]);
}
```

#### **Acceptance Criteria:**

- [ ] A new integration with the CodeClimate API is created.
- [ ] The repositories table is queried to retrieve the list of repositories.
- [ ] CodeClimate data is fetched for each repository and stored in a new dedicated table.
- [ ] The new database table is created with relevant fields (e.g., GPA, issues count, maintainability index).
- [ ] A periodic job or cron is set up to refresh the data from CodeClimate.

#### **Additional Context:**

This feature will allow us to monitor the code quality of our repositories using CodeClimate's metrics. By storing only relevant information, the table remains lightweight and easy to query for further use in dashboards or reporting.
